@startuml domain-diagram


package ブロガー集約 {
    class ブロガー {
        ブロガーID
        ニックネーム
        パスワード
        Email
        PRコメント
    }
}
note top
    - ニックネームは重複不可
    - Emailは重複不可
    - パスワードはハッシュ化される
end note


package 記事集約 {
    class 記事 {
        記事ID
        ブロガーID
        タイトル
        内容
        作成日時
        更新日時
        投稿日時
        公開設定
        ナイスリスト
        コメントリスト
        タグリスト

        訪問者コメント設定
        ブロガーコメント設定
        コメント一般公開設定
    }
}

note bottom
    - 公開設定は非公開がデフォルト
    - 作成日時と更新日時は記事を作成した日時で作成される。
    - タイトル、内容を更新すると更新日時が自動で更新される。
    - ビジターはビジターコメント設定がONの場合のみナイスできる
    - ブロガーはブロガーコメント設定がONの場合のみナイスできる
    - コメント一般公開設定がONの場合はブロガーおよびビジターどちらでもコメント内容を表示できる
    - コメント一般公開設定がOFFの場合は記事を投稿したブロガーのみがコメントを表示できる
    - 同一ブロガーが複数回ナイスすることはできない
    - 同一の記事に同一のタグをつけることはできない
end note

package 記事集約 {
    class コメント {
        コメントID
        記事ID
        ブロガーID
        内容
        投稿日時
    }
}
note top
    投稿日はコメント作成時の日時が設定される
end note

package 記事集約 {
    class ナイス {
        ナイスID
        ブロガーID
        記事ID
    }
}



ブロガー <-- 記事 : ブロガーID参照
ブロガー <- コメント : ブロガーID参照
ブロガー <- ナイス : ブロガーID参照
記事 <-left- コメント : 記事ID参照
記事 <-right- ナイス : 記事ID参照

@enduml
