version: '3.8'

services:
    db:
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./db/sql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - TZ=Asia/Tokyo
        command: ["mysqld", "--character-set-server=utf8mb4" ,"--collation-server=utf8mb4_unicode_ci"]
    api:
        image: hallog-api-dev
        ports:
            - 3000:3000
        volumes:
            - ./api/project:/project
            - api-node_modules:/project/node_modules
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - AUTH_SECRET=${AUTH_SECRET}
            - AUTH_ALGORITHM=${AUTH_ALGORITHM}
        restart: always

volumes:
    api-node_modules:
    db-data:
